from django.db import models
# Note: only saved the techniques, mitigation and detections that are relevant for campaigns (not all of them)

class Domain(models.TextChoices):
    ENTERPRISE = "enterprise-attack", "Enterprise" # stored value, human label
    MOBILE = "mobile-attack", "Mobile"
    ICS = "ics-attack", "ICS"

class Technique(models.Model):
    mitre_id = models.CharField(max_length=100, unique=True, null=True, blank=True)
    domain = models.CharField(max_length=50, choices=Domain.choices, default=Domain.ENTERPRISE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, default="")
    kill_chain_phases = models.JSONField(default=list, blank=True) # tactics the technique can be used for
    platforms = models.JSONField(default=list, blank=True) # to filter for only relevant platforms
    is_subtechnique = models.BooleanField(default=False) # parent technique could give a better overview
    created_date = models.DateTimeField(null=True, blank=True) # to find the newest created techniques
    parent_technique = models.ForeignKey(
        'self',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='subtechniques'
    )

    def __str__(self):
        return self.name

class Group(models.Model):
    mitre_id = models.CharField(max_length=100, unique=True, null=True, blank=True)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, default="")
    techniques = models.ManyToManyField(
        "Technique",
        related_name="groups",
        blank=True,
    )

class Campaign(models.Model):
    mitre_id = models.CharField(max_length=100, unique=True, null=True, blank=True)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, default="")
    last_seen = models.DateTimeField(null=True, blank=True)
    first_seen = models.DateTimeField(null=True, blank=True)
    techniques = models.ManyToManyField(Technique, related_name="campaigns", blank=True)
    summary = models.TextField(blank=True, default="", help_text="LLM generated summary of the campaign")
    attack_example = models.JSONField(blank=True, null=True)
    groups = models.ManyToManyField(Group, related_name="campaigns", blank=True)

    def __str__(self):
        return self.name

class CampaignGroupSimilarity(models.Model):
    campaign = models.ForeignKey("Campaign", on_delete=models.CASCADE, related_name="group_similarities")
    group = models.ForeignKey("Group", on_delete=models.CASCADE, related_name="campaign_similarities")
    score = models.FloatField()
    is_attributed = models.BooleanField(default=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("campaign", "group")


class Mitigation(models.Model):
    mitre_id = models.CharField(max_length=100, unique=True, null=True, blank=True)
    domain = models.CharField(max_length=50, choices=Domain.choices, default=Domain.ENTERPRISE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, default="")
    techniques = models.ManyToManyField(Technique, related_name="mitigations")
    summary = models.TextField(blank=True, default="", help_text="LLM generated summary of the mitigation")

    def __str__(self):
        return self.name

class Detection(models.Model):
    mitre_id = models.CharField(max_length=100, unique=True, null=True, blank=True)
    domain = models.CharField(max_length=50, choices=Domain.choices, default=Domain.ENTERPRISE)
    name = models.CharField(max_length=255)
    techniques = models.ManyToManyField(Technique, related_name="detections")

    def __str__(self):
        return self.name

class CampaignTechnique(models.Model):
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    technique = models.ForeignKey(Technique, on_delete=models.CASCADE)
    usage_description = models.TextField(
        blank=True,
        default="",
        help_text="Describes how this technique was used in this specific campaign"
    )

    usage_summary = models.TextField(
        blank=True,
        default="",
        help_text="A very short, simplified summary of the usage description, generated by LLM."
    )

    # will be set with classify_campaign_techniques.py
    selected_kill_chain_phase = models.CharField(max_length=50, blank=True, null=True)
    selected_tactic = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        unique_together = ("campaign", "technique")

    def __str__(self):
        return f"{self.campaign.name} - {self.technique.name}"


class Tactic(models.Model):
    mitre_id = models.CharField(max_length=100, unique=True, null=True, blank=True)
    domain = models.CharField(max_length=50, choices=Domain.choices, default=Domain.ENTERPRISE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, default="")
    techniques = models.ManyToManyField(
        Technique,
        related_name="tactics",
        blank=True,
    )
    def __str__(self):
        return self.name

class CampaignFAQ(models.Model):
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE, related_name="faqs")
    question = models.CharField(max_length=512)
    answer = models.TextField()
    is_ai_generated = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.campaign.name} - {self.question[:50]}"